# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: nas3f
google_analytics: nas3f
title: Nas3f

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Nasef

description: Stylish Jekyll Theme
author:
  name: Nas3f
  email: nnas3f@gmail.com
  github: nas3f
  twitter: nnas3f
  pinterest: 
  linkedin: 
  bio: Experimenter, Breaker , Security Lunatic
  email_md5: 4ec7fec11f5de851e3ba445b2b6a0450

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
 sidebar_background_image: https://scontent.faly3-1.fna.fbcdn.net/v/t1.0-9/82788824_2565868663694227_7779928344367202304_n.jpg?_nc_cat=109&_nc_ohc=j-v6au0UXL8AX8SViDc&_nc_ht=scontent.faly3-1.fna&oh=f7afb3913c8434fc15e79ddd199c5233&oe=5ECAE302

BASE_PATH:

plugins:
  - jekyll-paginate
